### ISSUE TITLE
Add release target to PSR4 build script

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#1]
Would be nice to have a `release` target that we can use after the `build` target to help automate the release process.

This would do the following (needs to be fully fleshed out):
- [x] Push generated Lite variation to Lite GitHub repo, with a commit message that contains the entire changelog for that particular release
- ...

**Comment by jaswrks** [comment]
I think this can be closed now. Would you agree?

**Comment by raamdev** [comment]
Yes. Thanks!
