### ISSUE TITLE
Automatic Slack Notifications

### ISSUE THREAD

**Issue by jaswrks** [websharks/phings#108]
It would be nice if there were some form of automatic Slack notification sent to everyone whenever anything new is released. Either an RC or a formal release, or when a bleeding-edge is updated by the project lead.

The notification should be low-key though, because it's likely to be followed-up by a more informative message from the lead in many cases. Also, it should be possible to opt-out of this behavior.

@raamdev Thoughts on this?

**Comment by raamdev** [comment]
I love this idea! I think you're right about keeping it short and sweet. I'd say posting something to the `#company` channel like, "A new version of [Software Name] has been released! [link to release on GitHub]".

**Comment by jaswrks** [comment]
## Required `.websharks.json` Config Keys

``` json
"phings": {
    "github": {
      "username": "",
      "email": "",
      "api_key": ""
    },
    "aws": {
      "access_key": "",
      "secret_key": "",
      "salt": ""
    },
    "slack": {
      "username": "",
      "email": "",
      "api_webhook_url": ""
    }
  }
```

**Comment by jaswrks** [comment]
Next Release Changelog:
- `adHocSlackNotify()` See: #108 and review README for this repo.
