### ISSUE TITLE
Auto-update @since PHPDoc during final release

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#109]
It would be really nice if during the final `phing release` (but NOT `phing release-rc`), if Phings could auto-update any occurrences of `@since 16xxxx` in PHP files for the project to use the version number begin released (e.g., `@since 160603`).

That would be one less step for me during a release. :-)

Note that this should NOT happen to an files in the `vendor/` directory. It should also NOT happen during the `phing release-rc`.

**Comment by jaswrks** [comment]
Next Release Changelog:
- Auto-replace `@since $v` or `@since [0-9]{2}[xX]{4}` during a release build. See: #109

**Comment by jaswrks** [comment]
@raamdev There is a bug in the latest version of the build system that causes `@since` tags to get mangled if they contain `xxxx` when you're doing a release. Reopening this issue.

**Comment by jaswrks** [comment]
Fixed in: https://github.com/websharks/phings/releases/tag/160624.36916
