### ISSUE TITLE
000000-dev => dev

### ISSUE THREAD

**Issue by jaswrks** [websharks/phings#124]
The dev branch will be referenced as just `dev` instead of `000000-dev`.
## Considerations
- [x] Update and release a new version of the Phing build system that references `dev`.
- [x] Update the websharks/hubflow repo and change `000000-dev` to just `dev`.
- [x] Run a search for `000000-dev` in the websharks/websharks-inc.com repo and update accordingly.
- [x] 👍 **Let's do it! :-)** Update the branch name in all repos that we have. `000000-dev` becomes `dev`. _This will be checked off once all repos are updated, following the instructions below._
  
  **Remaining Repos:**
  - [x] Comet Cache repos.
  - [x] Comment Mail repos.
  - [x] WP Redirects repo.

---
#### Rename Your Own Local Clone

``` bash
$ git checkout 000000-dev
$ git branch --move dev
```
#### Push `dev` to GitHub :octocat:

``` bash
$ git push --set-upstream origin dev
```
#### Change the Default Branch @ GitHub :octocat:

Visit: `https://github.com/websharks/[REPO]/settings/branches`

![](https://s31.postimg.org/7dcmy3xzv/dev.png)
#### Delete Old `000000-dev` Branch @ GitHub :octocat:

``` bash
$ git push origin --delete 000000-dev
```

_Or, you can simply visit the 'Branches' tab at GitHub and delete it that way._
#### Complete The Following Checklist (For Each of Your Repos)
- [ ] Notify all team members (in Slack) about this change and ask them to:
  
  ``` bash
  $ git fetch --all
  $ git checkout dev
  $ git branch --set-upstream-to=origin/dev
  $ git branch -D 000000-dev # Delete old 000000-dev locally.
  ```
##### If Your Repo Has Many Forks
- [ ] Post a new issue (announcement) in each repo that has several forks so that outside contributors will have a clue as to what is happening with the branch rename. You can use [this template I prepared](https://github.com/websharks/phings/issues/124#issuecomment-228717786).
- [ ] Add a note to the README file for each repo that has several forks so that outside contributors will have a clue as to what is happening with the branch rename. Link to the issue announcement you just created.

**Comment by jaswrks** [comment]
**Latest Phings:** https://github.com/websharks/phings/releases/tag/160627.38807
**Latest Hubflow:** https://github.com/websharks/hubflow/releases/tag/160627
**Latest HB Formulas:** https://github.com/websharks/homebrew-formulas/releases/tag/160627

**Comment by jaswsinc** [comment]
Referencing: https://github.com/websharks/homebrew-formulas/releases/tag/160627

**Comment by jaswrks** [comment]
## Attn: Contributors w/ a Fork

The `000000-dev` branch in this repo (i.e., the default branch) has just been renamed to `dev` (simpler, easier to type). **IMPORTANT:** This change may impact anyone who has a fork of this repo on GitHub. If you have any trouble in the future; i.e., errors about a missing branch or problems when trying to sync with the upstream repo, please follow these instructions to bring your fork up-to-date.

### Updating Your Fork (Instructions)

#### Update Your Local Clone

``` bash
$ cd [YOUR LOCAL REPO DIRECTORY]
$ git checkout 000000-dev
$ git branch --move dev
```

#### Push `dev` To GitHub Now

``` bash
$ git push --set-upstream origin dev
```

#### Delete Old `000000-dev` Branch

Go to GitHub and change the 'default' branch in your fork to `dev`

Visit: `https://github.com/[YOU]/[REPO]/settings/branches`

![](https://s31.postimg.org/7dcmy3xzv/dev.png)

Then run the following command to delete the old `000000-dev` branch from GitHub.

``` bash
$ git push origin --delete 000000-dev
```

_Or, you can simply visit the 'Branches' tab in your fork at GitHub and delete it that way._

### What's Next?

If you already followed [these instructions](https://help.github.com/articles/syncing-a-fork/) provided by GitHub in the past, you're all set. Nothing in this change should negatively impact an already-configured upstream remote. If you haven't followed those instructions (i.e., you don't yet have an upstream remote configured), you might want to take a moment to [do that now](https://help.github.com/articles/syncing-a-fork/).

**Comment by raamdev** [comment]
@J

**Comment by raamdev** [comment]
@jaswsinc FYI, I've checked off all the todos at the top of this issue. This issue can probably be closed now.

**Comment by jaswrks** [comment]
Cool!
