### ISSUE TITLE
Feature Request: `.build.php` Priority

### ISSUE THREAD

**Issue by jaswrks** [websharks/phings#127]
It is currently possible to name `.build.php` files in a way that dictates which directory they should run in; e.g., `.build.in-base-dir.php`, `.build.in-build-dir.php`. However, it would be nice if `.build.php` files could also be named in a way that dictates _when_ they are run; i.e., in what sequence.

For instance, I have a skeleton project that builds like other projects, but there are some things in the base directory that should be removed in order to keep it just a skeleton. Granted, that's a very special case, but that's what `.build.php` files are for. Having the ability to dictate _when_ they run, would, for instance, allow me to have a `.build.php` file that can run _after_ everything else is done.

**Comment by jaswrks** [comment]
Noting that _priority_ could also be applied to multiple `.build.php` files, where having the ability to control _when_ they run, could also allow for multiple `.build.php` files to run in a specific sequence together.

**Comment by jaswrks** [comment]
Noting that this now has a lower priority because I took a different approach in the skeleton project. Using a bash `./prepare` script instead: https://github.com/websharks/wp-sharks-skeleton-pro/blob/dev/prepare

**Comment by jaswrks** [comment]
Noting that prioritized `.build.php` files are accomplished using a numbered format. Instead of `.build.in-base-dir.php`, you can use `.build.in-base-dir.1.php`, `.build.in-base-dir.2.php`, etc.

Use a `.[number]` and please refrain from using a `-[number]`. This is so your numbered build files are also excluded properly from any final distro.

**Comment by jaswrks** [comment]
Noting that a numbered sequence currently requires that you also add the phase.

i.e., `.build.1.php` does not work.

But `.build.in-base-dir.1.php` does work, as does `.build.in-build-dir.1.php`

**Comment by raamdev** [comment]
@jaswsinc We should document all of this on [the Wiki](https://github.com/websharks/phings/wiki) for future reference. Would you mind creating a page for that? Even a rough draft that I can clean up would be fine. With all the changes, I'm not certain exactly how it works.

**Comment by jaswrks** [comment]
@raamdev Wiki article drafted here: https://github.com/websharks/phings/wiki/.build.php-Files

**Comment by raamdev** [comment]
@jaswsinc Awesome! Thank you very much.
