### ISSUE TITLE
Feature Request: TODO.md Exclusion

### ISSUE THREAD

**Issue by jaswrks** [websharks/phings#128]
It would be nice if we could add a `TODO.md` exclusion rule for distros, so that we can include a `TODO.md` file in the repo root directory without that ending up in the final distro.

**Comment by raamdev** [comment]
Couldn't this just go in the `.build.props`? I thought that's what `project_other_zip_tgz_fileset_exclusions` was for...

**Comment by jaswrks** [comment]
> Couldn't this just go in the .build.props?

That's right, yes. I just like to get things that are common to all of our projects into the build system so we won't need to define them on a per-project basis that way.
