### ISSUE TITLE
New Build Target: `release-test`

### ISSUE THREAD

**Issue by jaswrks** [websharks/phings#13]
```
$ phing -f .~build.xml release-test
```

A new build target could be added that runs all of the same release-related routines, but also sets a flag internally that prevents anything from actually being uploaded anywhere that could trigger a release.

Ideally, we could make this as much like a real release as possible. If that means uploading to servers, but with special suffixes to prevent release notifications from going out, that would fine with me.
### How much time should we spend on this?

I think it's worth the time to build a test for this, because it will make _using_ Phing to do releases much more feasible. Currently, the time between working on a release and making changes to the build script, to the codebase itself, and then forgetting how this actually works; is far enough apart that it makes it hard to trust the Phing build script like we should.

**Comment by raamdev** [comment]
> the time between working on a release and making changes to the build script, to the codebase itself, and then forgetting how this actually works; is far enough apart that it makes it hard to trust the Phing build script like we should.

I currently use the Phing build script to build the ZenCache Pro releases (RC and public) and then the real testing comes from actually testing the zip files produced by the build script, prior to actually uploading them anywhere. Even if we update the Phing build script to upload zip files somewhere, I'm _still_ going to want to test those zip files before I decide to publish them (even if the build script _can_ publish them for me, I'll want to test the produced zip files _before_ they are uploaded). I'm not sure how a new `release-test` target will change that.

**Comment by jaswrks** [comment]
Copy that. I see what you mean. I'm going to close this.
