### ISSUE TITLE
Improve @since replacement regex

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#133]
As of v160707.2080, if you accidentally enter an extra `x` in the `@since` date in your DocBlocks (e.g., `@since 16xxxxx`), Phings will ignore it. It would be nice if the regex that did the search looked for _any_ number of `x`'s up until the first whitespace character.

**Comment by jaswrks** [comment]
Next Release Changelog:
- Enhancing `@since` replacements and adding support for `@deprecated`. See: #130 and #133
