### ISSUE TITLE
Bug: `composer.json` Dependencies in Lite Variation

### ISSUE THREAD

**Issue by jaswrks** [websharks/phings#146]
@raamdev writes...

when building Comet Cache, the Lite distributable contains modules that should not be there (`src/vendor/websharks/js-minifier/`, `src/vendor/websharks/html-compressor/`, `src/vendor/websharks/css-minifier/`).

@jaswsinc writes...

I see. That's a bug. We need to find an elegant way of identifying dependencies that are not needed by the lite variation so that those can be excluded from the lite variation build.

**Comment by raamdev** [comment]
I suppose these could just go in the `.build.props` file via `project_lite_other_zip_tgz_fileset_exclusions`.

**Comment by raamdev** [comment]
Noting that I ran into this issue again during the Comment Mail v161118 release.

**Comment by raamdev** [comment]
Related: https://github.com/websharks/phings/issues/150
