### ISSUE TITLE
Build system should strip unnecessary files from distributables

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#150]
@jaswsinc writes ([in Slack](https://websharks.slack.com/archives/comet-cache/p1481908701000047)):

> the ﻿⁠⁠⁠⁠src/vendor/bin﻿⁠⁠⁠⁠ directory (and contents) does not need to be in there. Things like `﻿⁠⁠⁠⁠README.md`﻿⁠⁠⁠⁠, `﻿⁠⁠⁠⁠CHANGELOG.md`﻿⁠⁠⁠⁠, ﻿⁠⁠⁠⁠`CHANGELOG.mdown`﻿⁠⁠⁠⁠, ﻿⁠⁠⁠⁠R`EADME.mdown`﻿⁠⁠⁠⁠, ﻿⁠⁠⁠⁠`.php_cs`﻿⁠⁠⁠⁠, ﻿⁠⁠⁠⁠`circle.yml﻿⁠⁠⁠⁠`, `﻿⁠⁠⁠⁠.travis-scripts﻿⁠⁠⁠⁠`, ﻿⁠⁠⁠⁠`.gitkeep`﻿⁠⁠⁠⁠, ﻿⁠⁠⁠⁠`phpunit.xml`﻿⁠⁠⁠⁠, ﻿⁠⁠⁠⁠`phpunit.xml.dist`﻿⁠⁠⁠⁠, and ﻿⁠⁠⁠⁠`Makefile﻿⁠⁠⁠⁠` in some of the dependency directories do not need to be in the final distro either.
> 
> In the Lite build, many of the additional dependencies are in there, even though we added support for ﻿⁠⁠⁠⁠`require-lite:{}﻿⁠⁠⁠⁠` in ﻿⁠⁠⁠⁠`composer.json﻿⁠⁠⁠⁠` via the Phing build system. So this part is not working in the Phing build system.

Related: https://github.com/websharks/phings/issues/146
Related: https://github.com/websharks/phings/issues/141

**Comment by raamdev** [comment]
We should be excluding from the final distributables anything in the `src/` directory that is not necessary for the plugin to run, e.g., `src/vendor/monolog/monolog/doc/` and (maybe?) `src/vendor/symfony/debug/`.

**Comment by raamdev** [comment]
Noting also that we do have the `project_other_zip_tgz_fileset_exclusions` property in the `.build.props` file that could be used to ensure certain files/directories are excluded from the distributable, so maybe we just need to keep the exclusions there more up-to-date?

**Comment by jaswrks** [comment]
I think if it's something fairly common and easy for us to exclude across all builds for any project, then we should try to do that. An example would be a directory with the name `/tests/`, which we exclude already. I think a directory named `/debug/` or `/doc/` could lead us to false-positives in other projects, so those would be good candidates for `project_other_zip_tgz_fileset_exclusions`.

**Comment by jaswrks** [comment]
@raamdev See https://github.com/websharks/phings/commit/d8ab74b6bff0670a8b3bf9ea5785bdcdf1c29803 where I've added some additional patterns that are now excluded from all builds, across all projects.
