### ISSUE TITLE
CHANGELOG.md $v does not get updated

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#155]
Using Phings v161222.732 in the Comet Cache Pro repo, I did the following:

```
$ phing release-rc
$ phing full-build-all
```

As per [the wiki](https://github.com/websharks/phings/wiki/GitHub-Releases#changelog-format-tip), I expected that to replace `= $v =` in the `CHANGELOG.md` file with the release version (`v161223-RC`, in this case), however that did not happen. `$v` remained in the `CHANGELOG.md` file and I had to manually update it and do my final commit before publishing the release with a final `phing release-rc`.

**Comment by jaswrks** [comment]
This is a part of the upcoming release.
The `= $v =` format will get picked up starting with the next release.
I jumped the gun a bit whenever I used that in the Comet Cache changelog.

**Comment by raamdev** [comment]
@jaswsinc Ah, got it. Thank you.
