### ISSUE TITLE
-lite target corrupts binary files

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#23]
When building the Lite version of ZenCache with Phings `v151127.324`, the `-lite` target corrupts binary files and results in `0` byte images in `src/client-s/images/`. 

After a lot of trial-and-error, I narrowed the issue down to the [Namespace Replacement fileset](https://github.com/websharks/phings/blob/151127.324/src/psr4/targets/lite.xml#L114-L116) and the [Strip Pro Tokens fileset](https://github.com/websharks/phings/blob/151127.324/src/psr4/targets/lite.xml#L164-L166). 

The problem is that the filesets, which only _exclude_ `src/vendor/**`, end up _including_ binary files. When the `<replaceregexp>` filter is applied to those binary files, they become corrupted.

**Comment by jaswrks** [comment]
Next Release Changelog:
- Bug fix. Binary file corruption, no more! See: https://github.com/websharks/phings/issues/23
