### ISSUE TITLE
Feature Request: Project-specific file exclusions when building packages

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#25]
Since the Lite-generated version of project often does not include all of the same files as the Pro version, it would be nice to be able exclude certain files when building the package(s) for the Lite version. (For example, the Lite-generated version of ZenCache has a bunch of empty PHP files for the CDN Utils, Auto-Cache Engine, etc.; this could confuse site owners and make them think that they have a corrupt copy of the plugin.)

Additionally, it would be nice if the Pro version could also have project-specific exclusions.

These exclusions could be defined in the `.build.props` file and then read during the build process, that was the project-specific exclusions live inside the repo for each project and do not need to be included in the Phing build scripts themselves.

**Comment by jaswrks** [comment]
Next Release Changelog:
- New build properties that allow for project-specific PHAR and ZIP/TGZ exclusions. See: https://github.com/websharks/phings/issues/25
