### ISSUE TITLE
-lite target namespace replacement needs to consider some non-PHP files

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#31]
The `-lite` target currently only runs the namespace replacements [in `*.php` and `**/**.php` files](https://github.com/websharks/phings/blob/160107/src/psr4/targets/lite.xml#L117-L118), however that excludes the namespace replacement required for the [`src/includes/templates/advanced-cache.txt` in ZenCache](https://github.com/websharks/zencache-pro/blob/160103/src/includes/templates/advanced-cache.txt#L7).

What we need is an additional `project_lite_other_ns_replace_files_pattern` property that we can add to the project-specific build files so that we have a place to make special considerations like `advanced-cache.txt` in ZenCache.

**Comment by jaswrks** [comment]
:+1:

**Comment by jaswrks** [comment]
Next Release Changelog:
- New build property: `project_lite_text_domain_regex_replacement_pattern`. See: https://github.com/websharks/phings/issues/31
- Reflexive processing now takes place in `.x-php` files as well. See: https://github.com/websharks/phings/issues/31
