### ISSUE TITLE
Increase verbosity of property names

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#33]
Forked from https://github.com/websharks/phings/pull/32#issuecomment-170246019.

@jaswsinc writes...

> I wish I had named those differently from the start. I was trying to keep the names a bit shorter, but in practice it seems like the `.build.props` file is easier to deal with when it is verbose.
> 
> For instance, it's not clear (even to me), whenever I glance over the `.build.props` file what `project_sns` really is. I find myself looking back through the build script so I can try and remember what it was for.
> 
> > The more projects we have that are using the Phing build scripts, the more room there is for error.
> 
> Exactly, yes. At some point, if you agree, I'd like to rename the `ns` and `sns` properties to something more verbose. However, we will need to add back compat. for the shorter names too, if we do that.

**Comment by raamdev** [comment]
Related PR: https://github.com/websharks/phings/pull/37

**Comment by jaswrks** [comment]
Next Release Changelog:
- Noting that many property names defined in `.build.props` changed. See: https://github.com/websharks/phings/issues/33
  - `project_org` is now `project_owner`
  - `project_ns` is now `project_namespace`
  - `project_sns` is now `project_sub_namespace`
  - `project_lite_ns` is now `project_lite_namespace`
  - `project_lite_sns` is now `project_lite_sub_namespace`
  - `project_php_up_to_version` is now `project_php_tested_up_to_version`
  - `project_wp_up_to_version` is now `project_wp_tested_up_to_version`
