### ISSUE TITLE
-lite target doesn't exclude Pro translation file

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#34]
See related discussion here: https://github.com/websharks/zencache-pro/pull/201#issuecomment-170346701

We need to update [this fileset](https://github.com/websharks/phings/blob/160107/src/psr4/targets/lite.xml#L28-L30) to add:

```
<exclude pattern="**/${project_slug}.pot" />
```

**Comment by jaswrks** [comment]
Next Release Changelog:
- Bug fix. `<exclude pattern="**/${project_slug}.pot" />`. See: #34
