### ISSUE TITLE
Separate build procedures from release procedures

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#4]
@jaswsinc writes (in https://github.com/websharks/phings/pull/3#commitcomment-11271750)... 

> Another idea, is that we could create a separate build file for releases

I actually like that idea. I also see the release-related targets becoming lengthy over time and I like the idea of separating the logic of those two things, so that all build-related stuff goes in `.build.xml` and all release-related stuff goes in `.build-release.xml`. 

Another reason for this is that we may find it necessary to have product-specific release procedures that are not very generic. It would be better to have those separate from the build procedure itself, since that will likely remain the same for each project.

**Comment by jaswrks** [comment]
Resolved by: https://github.com/websharks/phings/pull/15
