### ISSUE TITLE
.sass-cache is not excluded when generating Lite version

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#40]
When generating a Lite Comet Cache build, `/src/client-s/css/.sass-cache/` does not get excluded from the distributable. The `.sass-cache` directory should never be included in a distributable.

**Comment by raamdev** [comment]
It appears this is still not working:

```
zencache-pro/src/client-s/css/.sass-cache/ff30ec8c670a5535fd022feef4bca79fa80545d1/_sharkicons.scssc
```

I think the problem is that we're not gobbling up the end of the path:

```
<exclude name="**.sass-cache**" />
<exclude name="**/**.sass-cache**" />
```

**Comment by jaswrks** [comment]
Next Release Changelog:
- Excluding `.sass-cache` (directories, not files) from distros and PHAR files.
