### ISSUE TITLE
Remove `websharks/wp-core` from rebranded libraries.

### ISSUE THREAD

**Issue by jaswrks** [websharks/phings#43]
I have decided that the websharks/wp-core project will be a plugin dependency in WordPress itself; it will itself be a WordPress plugin. That will make it possible for multiple plugins to share the same websharks/wp-core plugin.

In this way, small plugins can be developed and added to a site, capable of taking advantage of the websharks/core and websharks/wp-core libraries, but without the overhead of shipping each small plugin with the larger framework upon which it is being developed.

For this reason, the websharks/wp-core should be excluded from the rebranding target in our Phing build script. It doesn't need to undergo any namespace alternations. That will happen to the websharks/core which is bundled together with the websharks/wp-core plugin.

**Comment by jaswrks** [comment]
@raamdev Just a heads up on this change. I merged this into the dev branch.

**Comment by jaswrks** [comment]
Next Release Changelog:
- Remove `websharks/wp-core` from rebranded libraries.

**Comment by raamdev** [comment]
Makes sense to me. Thanks for the heads up!
