### ISSUE TITLE
websharks/core Rebrand should include WP theme/plugin i18n conversions.

### ISSUE THREAD

**Issue by jaswrks** [websharks/phings#45]
Whenever the websharks/core is rebranded as a part of a WP theme/plugin, we should also look for any instances of `__()` in the websharks/core package, and be sure to force a hard-coded text domain into these calls in order to make the complete final plugin translation-ready.

**Comment by jaswrks** [comment]
Next Release Changelog:
- Rebrand subroutines now include websharks/core i18n alternations for WP themes/plugins.

**Comment by raamdev** [comment]
:+1: Thanks!
