### ISSUE TITLE
Improve how Phing is used during testing of feature branches

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#49]
Right now we run `phing` to build a distributable that can be installed and tested on a WordPress site, however running `phing` currently changes version numbers and does other unnecessary (for testing purposes) things like regenerating the translation files.

@raamdev writes in https://websharks.slack.com/archives/company/p1456404698000093

> I was thinking that `phing` itself should be what everybody can run without affecting the version numbers, and then I could just run `phing release` or some other target whenever I'm doing a release.

**Comment by jaswrks** [comment]
Sorry to step on your toes here, but I started working on some larger changes for the WP Sharks Core, and I went ahead and added this in. Still a work-in-progress at the moment, but it will be ready to merge sometime tomorrow. https://github.com/websharks/phings/pull/50

**Comment by jaswrks** [comment]
Closed by https://github.com/websharks/phings/pull/50

**Comment by raamdev** [comment]
Cool. Thanks for taking care of this! :-)
