### ISSUE TITLE
Strip sourceMappingURL from minified files

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#68]
See https://github.com/websharks/comet-cache/issues/732.

> The `*.min.css` files included with the distributable zip file currently contain a comment at the bottom that points to source maps (e.g., `/*# sourceMappingURL=admin-bar.min.css.map */`). 

These `sourceMappingURL` comments are not necessary and need to be stripped out during the build process.

@jaswsinc Any thoughts on which target this routine should go in?

**Comment by jaswrks** [comment]
I think a new target would probably be warranted for that. Something along the lines of `js-css.xml` that would run after the `dotbuilds.xml` file: https://github.com/websharks/phings/blob/000000-dev/src/psr4/targets.xml#L16

**Comment by raamdev** [comment]
Edit: Forked to separate GitHub issue: https://github.com/websharks/phings/issues/81

**Comment by raamdev** [comment]
Next Release Changelog: 
- Support for stripping sourceMappingURL comments from minified JS/CSS files via a new `-js-css` target. See https://github.com/websharks/phings/issues/68.
