### ISSUE TITLE
Build process generates Lite version with Pro Assets (instead of Lite assets)

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#7]
The build script currently generates the Lite version from the Pro version, but this results in a Lite version which includes the `assets/` directory from the Pro version, which is different than the `assets/` directory for the Lite version (the Lite version includes assets for WordPress.org, e.g., plugin screenshots). 

We need to figure out how we're going to maintain both asset directories, or if we'll maintain all of the assets in a single `assets/` directory inside the Pro repo, but then exclude Pro-only assets during the Lite build process, and exclude Lite-only resources from the Pro build process, so that we end up with generated Pro and Lite versions that only include the appropraite files in the assets directory (we can maintain the list of appropriate files in the build script itself, or better yet, in a separate product-specific release build script; see https://github.com/websharks/phings/issues/4).

@jaswsinc Thoughts?

**Comment by jaswrks** [comment]
> maintain all of the assets in a single assets/ directory inside the Pro repo, but then exclude Pro-only assets during the Lite build process

I'm with you there. I think that's a good idea.

> so that we end up with generated Pro and Lite versions that only include the appropraite files in the assets directory (we can maintain the list of appropriate files in the build script itself

I got confused on this at first, but now I see what you mean. I think we should just keep _all_ of the `/assets` in the pro repo, and exclude them entirely from the lite repo. If we need something from the `/assets` directory we can get it from the pro repo.

**Comment by raamdev** [comment]
@jaswsinc What do you think about storing the Lite plugin assets in `assets/lite-assets/` in the Pro repo? The only thing we use the `lite-assets/` for is pushing things like plugin screenshots to WordPress.org via SVN.

The `-lite` target could then be updated to copy `lite-assets/` to `assets/` during the build process so that `zencache-pro/.~build/zencache/assets/` includes the Lite assets (instead of the Pro assets as it does now) after running a build.

As of now, the ZenCache Lite assets are the only thing that's missing from the ZenCache Pro repo, so I'd like to figure out where we should put those in the Pro repo.

**Comment by jaswrks** [comment]
I agree. Sounds like a good idea to me! :-)

**Comment by jaswrks** [comment]
I just ran through a couple of tests with this and now I'm seeing that I missed this point that you made before. I didn't take enough time to really comprehend before. Sorry.

You wrote previously...

> The -lite target could then be updated to copy lite-assets/ to assets/ during the build process so that zencache-pro/.~build/zencache/assets/ includes the Lite assets (instead of the Pro assets as it does now) after running a build.

So I have a question about this.

Why are we including assets (of any kind) in the final build? In my view, the build should be ready for distribution. We don't distribute any of the assets.

Or are you talking about an automatic lite repo generation in some way?

---

I do agree with the rest of what you said though...

> As of now, the ZenCache Lite assets are the only thing that's missing from the ZenCache Pro repo, so I'd like to figure out where we should put those in the Pro repo.

I think the `zencache-pro/assets/` directory should contain _all_ assets for both versions of the plugin. This way the lite version is really nothing more than a carbon copy of the pro version, with a few modifications that occur in the build process. I don't see us needing to have any assets in a lite repo.

My vote is that we start moving all of the assets into the pro repos that we have, and clear them out of the lite repos entirely. _Except for free plugins that don't have a pro repo. Those will just keep their assets in the only repo that we have for them—the lite repo._

---

Taking that a step further, we might also think about creating an orphan branch for assets and move them out of the 000000-dev & master branches altogether.

I was _forced_ to do this recently while working with improvements to our Git deployment process at [intellicache.me/branches](https://github.com/websharks/intellicache.me/branches) and a couple other sites. Why?  LFS is still a very young protocol, it has only very basic functionality that doesn't consider everything that Git can do. For instance, whenever you introduce more than one remote (e.g., a `www` remote), which does not support LFS, things start to get hairy.

Moving them into a separate branch seems to be a nice workaround.

Here's what I propose.

```
$ git checkout --orphan lfs
$ git rm -rf .
```

Then put the `assets/` directory in the orphaned `lfs` branch, and remove them from the other branches. With that done, we no longer need to consider assets in our build process at all.

**Comment by raamdev** [comment]
@jaswsinc writes...

> We don't distribute any of the assets.

Don't we? Lite assets get pushed to WordPress.org for the plugin page there. In my mind, those assets _do_ get distributed, just not as part of the plugin zip file itself.

Part of "building and releasing a Lite version" is pushing the changes to WordPress.org, and part of pushing the changes to WordPress.org is checking if any `assets/` changed. If they did, those need to be updated/deleted/pushed via SVN to WordPress.org as well.

---

> I think the `zencache-pro/assets/` directory should contain all assets for both versions of the plugin.

Right, that was my understanding as well... 

> My vote is that we start moving all of the assets into the pro repos that we have, and clear them out of the lite repos entirely.

That's fine with me. We just need to keep track of which assets belong to the Lite version (which is why I chose to put them in a separate directory (`assets/assets-lite/`), as opposed to mixing them with the other assets in `assets/`.

As I noted above, Lite assets are somewhat special in that they _are_ actually part of a release. Screenshots that appear on WordPress.org might change when a new feature gets added or something gets moved around. The banner image that shows up on the WordPress.org plugin page might change.

The Lite assets and their filenames (namely screenshots) are also linked with the `readme.txt` file for the Lite plugin in that the `readme.txt` file defines which screenshots show up on the WordPress.org plugins page, so again, the Lite assets are more tied to the actual plugin release than the Pro assets (which are really just assets related to the project in general; any Pro Plugin-specific assets actually live inside the Pro plugin itself, in `src/client-s/`).

**Comment by raamdev** [comment]
> Taking that a step further, we might also think about creating an orphan branch for assets and move them out of the 000000-dev & master branches altogether

We can't (and shouldn't) do that with the Lite assets for the reasons mentioned above.

**Comment by raamdev** [comment]
> Why are we including assets (of any kind) in the final build?

Right now we don't have the push to WordPress.org via SVN process automated with the build scripts, so after building a Lite version of the plugin the following still needs to happen to complete a release:
- Copy plugin files to `~/Projects/svn/zencache/trunk/`
- Copy changed assets (if any) to `~/Projects/svn/zencache/assets/`
- Commit and push changes to WordPress.org
- Create and push new version tag to WordPress.org

My reason for including the Lite assets in the build process was that I was going to then copy `.~build/zencache/assets/*` to my `~/Projects/svn/zencache/assets/` directory. 

Eventually, I'd like to automate even that process, perhaps by automatically checking out the repo from WordPress.org into the `.~build/` directory, updating the `assets/` and `trunk/`, then committing the changes and creating the tag.

However, automating that process makes me a little nervous. I like to be 100% sure that the code I'm pushing to WordPress.org has been tested, so I only push code that I've first installed on my local test site to confirm there are no disasters. Then I just unzip _that_ tested zip file, and copy the files to `trunk/` and push to WordPress.org.

**Comment by jaswrks** [comment]
> Part of "building and releasing a Lite version" is pushing the changes to WordPress.org, and part of pushing the changes to WordPress.org is checking if any assets/ changed. If they did, those need to be updated/deleted/pushed via SVN to WordPress.org as well.

Right. Great point.

> That's fine with me. We just need to keep track of which assets belong to the Lite version (which is why I chose to put them in a separate directory (assets/assets-lite/), as opposed to mixing them with the other assets in assets/.

Well, maybe (since you already have them separated in this way), we can copy them from the pro repo into the lite SVN repo whenever one of us builds this automation into the phing script. That way they would not need to live in the lite repo.

We are already manipulating things to go from PSR-style repos and Git as our version control system, into a makeshift SVN repo in order to get them on WordPress.org. So it seems like copying the assets from zencache-pro/assets/lite is OK too.

> Eventually, I'd like to automate even that process, perhaps by automatically checking out the repo from WordPress.org into the .~build/ directory, updating the assets/ and trunk/, then committing the changes and creating the tag.

Right. I'm with you there. Sounds awesome!

> We can't (and shouldn't) do that with the Lite assets for the reasons mentioned above.

Hmm. Yeah, that seems like it could really start to complicate things in the phing script; i.e., we would need to switch branches while the script is running, on top of everything else.

**Comment by raamdev** [comment]
> That way they would not need to live in the lite repo.

Right, they don't need to live in the Lite repo now. They have already been moved into the Pro repo (see https://github.com/websharks/zencache-pro/tree/000000-dev/assets/assets-lite), so we could safely delete them from the Lite repo altogether right now.

**Comment by raamdev** [comment]
> That way they would not need to live in the lite repo.

By "lite repo" I think you were referring to the generated-Lite `.~build/` directory. I misunderstood "lite repo" as meaning the Lite repo on GitHub.

Yes, I agree. There's really no reason other than for clarity to copy `assets/assets-lite/` to `assets/` in the generated `.~build/` directories. I'm perfectly fine with removing that part of the build script (and the associated `.build.props` properties) if you'd like. :-)

**Comment by jaswrks** [comment]
> By "lite repo" I think you were referring to the generated-Lite .~build/ directory

Yes, that's what I meant. I agree that there is really no reason for us to have a separate lite repo at GitHub now that the pro repo is public anyway.

**Comment by jaswrks** [comment]
> Yes, I agree. There's really no need other than for clarity to copy assets/assets-lite/ to assets/ in the generated .~build/ directories. I'm perfectly fine with removing that part of the build script (and the associated .build.props properties) if you'd like. :-)

I don't have anything against you doing it that way. Whatever makes the build process easier and improves clarity is good with me. I was trying to find a way to get these assets out of the picture entirely is all. However, now that you bring up the lite repo needing assets I see that really is not feasible.

**Comment by raamdev** [comment]
Closing this issue as resolved now that we've moved the Lite assets to the Pro repo (`assets/assets-lite/`).
