### ISSUE TITLE
-lite target should exclude Pro-only files

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#73]
The idea is to be able to add a new flag, `/*[pro strip-file-from="lite"]*/`, to the top of any files that are Pro-only files that should not be included in the generated Lite version.

Then, we can update the `lite.xml` target to include the following [right after copying the Pro files to the Lite staging area](https://github.com/websharks/phings/blob/160410/src/psr4/targets/lite.xml#L33):

```
<delete>
  <fileset dir="${project.basedir}/.~build/${project_lite_slug}">
    <contains text="/*[pro strip-file-from="lite"]*/" />
  </fileset>
</delete>
```

---

Jason and I have been discussing this issue a lot on Slack; see https://websharks.slack.com/archives/phings/p1460243931000102 for more details.

---

Also noting that this Comet Cache issue depends on Phings being updated to exclude Pro-only files: https://github.com/websharks/comet-cache/issues/709

**Comment by raamdev** [comment]
Also noting here that once this work has been completed, we can update the projects that are using the Lite target (e.g., Comet Cache and Comment Mail) and simplify their `.build.props` file. 

Right now we're using [`project_lite_other_phar_fileset_exclusions` and `project_lite_other_zip_tgz_fileset_exclusions`](https://github.com/websharks/comet-cache-pro/blob/160227/.build.props#L13-L14) to exclude the Pro-only files from the distributions, but once we exclude the Pro-only files earlier in the Lite build process by adding a `/*[pro strip-file-from="lite"]*/` flag to the tops of the relevant files, many of those additional exclusions in `.build.php` won't be necessary.

**Comment by jaswrks** [comment]
Next Release Changelog:
- Support for `/*[pro strip-file-from="lite"]*/`. See: #73

**Comment by raamdev** [comment]
@jaswsinc I'm wondering if we should change `strip-file-from` to `exclude-file-from`. That seems more appropriate and less easy to confuse with `strip-from`, which I've already done at least once. That would give us the following:

```
/*[pro exclude-file-from="lite"]*/
```

and

```
/*[pro strip-from="lite"]*/
/*[/pro]*/
```

I can make these changes and submit another PR if you agree.

**Comment by raamdev** [comment]
@jaswsinc I'm about to update the Comet Cache Pro-only files with this marker in preparation for publishing an RC—I just wanted to see if you agreed with changing the name or if you'd rather stick with `strip-file-from`.

**Comment by jaswrks** [comment]
Agree. I like `exclude` better also, but if we can support either/or that'd be great.

**Comment by raamdev** [comment]
> support either/or

Hmm, how would that work? Apply two regexes to the file in succession, one for each?

**Comment by jaswrks** [comment]
Something like this maybe.

``` xml
<containsregexp expression="\/\*\!?\[pro (?:exclude|strip)\-file\-from\=['&quot;]lite['&quot;]\]\*\/" />
```

**Comment by raamdev** [comment]
:facepalm: Right, of course.
