### ISSUE TITLE
-lite target should be independent from building the Pro version

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#75]
_Forking from https://github.com/websharks/comet-cache-pro/pull/240#issuecomment-207978175._

The `-lite` target currently runs as part of the main `-build` target, which builds the Pro version first and then [re-runs](https://github.com/websharks/phings/blob/160410/src/psr4/targets/lite.xml#L265-L272) the entire build process [on a copy](https://github.com/websharks/phings/blob/160410/src/psr4/targets/lite.xml#L27-L32) of the Pro files in the Lite staging area. 

The `-config` target (the first target called by the `-build` target) sets this up by [detecting](https://github.com/websharks/phings/blob/160410/src/psr4/targets/config.xml#L49-L76) if the `-lite` target is applicable and then the `-lite` target [uses that to decide](https://github.com/websharks/phings/blob/160410/src/psr4/targets/lite.xml#L11-L18) if it should re-run the build process again for a Lite version.

Here's why we should separate out the logic a bit 
- This is [confusing](https://github.com/websharks/comet-cache-pro/pull/240#issuecomment-207978175).
- Every time we build the Lite version, we need to build the Pro version—we should be able to do one without the other.
- This is confusing.

**Comment by raamdev** [comment]
See also: https://github.com/websharks/phings/issues/80

**Comment by jaswrks** [comment]
This will be improved by: https://github.com/websharks/phings/pull/83

**Comment by jaswrks** [comment]
Resolved by https://github.com/websharks/phings/releases/tag/160416
