### ISSUE TITLE
-push-lite-variation target doesn't generate Lite commit message

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#8]
The routine in the `-push-lite-variation` target that generates the commit message (`.~commit.msg`) using the `CHANGELOG.md` file is currently broken. While the `sed` commands are correct (and work fine if you run them from the terminal), the `.~commit.msg` file always ends up empty when running the `-push-lite-variation` target, so the build script cannot commit the changes.

**Comment by jaswrks** [comment]
Noting that this routine that you built is now a file of its own.
`src/psr4/targets/push-lite.xml`

**Comment by jaswrks** [comment]
I'm not great with `sed`, so I'm not entirely sure about the magic that you're doing here. However, I noticed there is no dollar sign in front of `{project_version}`. Not sure if that's a problem or not, but it caught my attention. Maybe that should be: `${project_version}` ?

https://github.com/websharks/phings/blob/feature/4/src/psr4/targets/push-lite.xml#L108

**Comment by jaswrks** [comment]
Am I correct that this line is just to print the changelog in the output?
https://github.com/websharks/phings/blob/feature/4/src/psr4/targets/push-lite.xml#L110

**Comment by raamdev** [comment]
> I'm not great with sed, so I'm entirely sure about the magic that you're doing here.

The goal there was to extract the entire changelog entry in `CHANGELOG.md` for `${project_version}` , the relevant section starting with `= vXXXXXX =` (i.e., `= ${project_version} =`), and then writing that entire version's changelog entry to `~.commit.msg`. The following line cleans up (removes) the bottom two lines in `~.commit.msg` because the first `sed` command captured a blank line and the following version header. 

The missing `$` looks wrong to me too. I did have this entire section of the build script working properly at one point, but the last time I remember using it that specific section (automatically generating a commit message using the changelog from `CHANGELOG.md`) was _not_ working properly. We then reverted ZenCache Lite to the old codebase, so this Lite generation part of the build script was not used and I stopped working on it. I created this GitHub issue as a way of remembering that the problem existed. :-)

> Am I correct that this line is just to print the changelog in the output?

That is correct.

**Comment by jaswrks** [comment]
:+1:

**Comment by jaswrks** [comment]
This will be fixed by: https://github.com/websharks/phings/pull/83

**Comment by jaswrks** [comment]
Resolved by https://github.com/websharks/phings/releases/tag/160416
