### ISSUE TITLE
-js-css target should modify .~build/ files and not the working directory

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#81]
_Forking from https://github.com/websharks/phings/issues/68#issuecomment-208425403._

The [new `-js-css` target](https://github.com/websharks/phings/commit/5e2848ae27fc0bb7948d2615b8c22e1a297cc46a) currently [modifies files in the repo](https://github.com/websharks/phings/commit/5e2848ae27fc0bb7948d2615b8c22e1a297cc46a#diff-836025db6b3564e92426bd1c15f48bedR14). It should only modify files in `.~build/` (see [discussion](https://github.com/websharks/phings/issues/76#issuecomment-207992890)). 

However, we can't change it to modify files in `.~build/` until we modify the rest of the build system to allow for sourcing the packages from `.~build/`. (Currently packaging happens _before_ `.~build/` is populated and the distributable packages are sourced from the repo directory, not the `.~build/` directory.)

This work will be related to https://github.com/websharks/phings/issues/80.

**Comment by jaswrks** [comment]
Thanks for opening this. I began some work on this over the weekend so I now need to pull together some of the recent changes you've added to that and then open a PR for your review. I worked to better organize the targets and there are a few changes throughout that make this possible.

**Comment by jaswrks** [comment]
This will be corrected by: https://github.com/websharks/phings/pull/83

**Comment by jaswrks** [comment]
Resolved by https://github.com/websharks/phings/releases/tag/160416
