### ISSUE TITLE
-lite target namespace replacements don't account for all scenarios

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#82]
During the Comet Cache v160412-RC release and subsequent testing, I discovered that the Lite version produced a fatal error on the front-end. I tracked it down to [`src/includes/functions/i18n-utils.php`](https://github.com/websharks/comet-cache-pro/blob/160412-RC/src/includes/functions/i18n-utils.php) where the following references to `CometCache\Pro\` were not being replaced with `CometCache\` by [the namespace replacements in the Phing `-lite` target](https://github.com/websharks/phings/blob/160411/src/psr4/targets/lite.xml#L118-L139):

``` php
    function __($string, $text_domain)
    {
        return \WebSharks\CometCache\Pro\__($string, $text_domain);
    }
```

``` php
    function __($string, $text_domain)
    {
        return \WebSharks\CometCache\Pro\__($string, $text_domain);
    }
```

I manually fixed the problem in the distributable for Comet Cache Lite v160412-RC, but we should try to get this fixed before the GA release on April 15th.

**Comment by jaswrks** [comment]
This will be corrected by: https://github.com/websharks/phings/pull/83

**Comment by jaswrks** [comment]
Resolved by https://github.com/websharks/phings/releases/tag/160416
