### ISSUE TITLE
Improve Composer dependency handling in Lite build

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#88]
@raamdev writes...

> I noticed that the `composer.json` file that ends up in Lite-generated build includes a reference to the `html-compressor`; that shouldn't be in there, should it? https://github.com/jaswsinc/comet-cache/blob/000000-dev/composer.json#L34
> And also references to `css-minifier` and `js-minfier` in https://github.com/jaswsinc/comet-cache/blob/000000-dev/composer.lock

@jaswsinc writes...

> Ah, right. Nope, those don't ​_need_​ to be in there. We probably need to come up with a system for handling Composer dependencies better in the lite build. Another area that needs improvement with respect to Composer, is with `require-dev`. Currently, I have hard-coded exclusions for Bourbon and the i18n tools package, but really those should be excluded automatically from the final ZIPs, because those are for devs only

**Comment by raamdev** [comment]
Related: https://github.com/websharks/phings/issues/90

**Comment by raamdev** [comment]
@jaswsinc I'm labeling this a `bug`, since my feeling is that those non-Lite Composer dependencies really do not belong in the Lite version at all and right now those will make it into a public Lite release unless we remember to manually remove them. That sort of defeats the whole purpose of using the build system in the first place (i.e., to automate all of this stuff).

**Comment by jaswrks** [comment]
Agree. I'll try to come back to this sometime this week and work to improve Composer handling overall in the Phing system. It seems that we have identified several areas that need improvement, including the related: https://github.com/websharks/phings/issues/90 that you mentioned.

**Comment by jaswrks** [comment]
Resolved in the release of v160526.
https://github.com/websharks/phings/releases/tag/160526
