### ISSUE TITLE
Improve Composer `require-dev` During Build

### ISSUE THREAD

**Issue by jaswrks** [websharks/phings#90]
During the build process (i.e., in the `.~build/[dir]` phase), we should run Composer a second time and with an additional flag that will be sure to _exclude_ all `require-dev` dependencies, as these should never be included in any official build of the software for redistribution.

At the moment, we have [some hard-coded exclusions](https://github.com/websharks/phings/blob/160418/src/psr4/setups/patterns/zip-tgz.xml#L37-L41) to work around this issue already, but moving forward this is going to become a bigger problem. Particularly when it comes to the WPSC.

Referencing `install` option: `--no-dev`:
https://getcomposer.org/doc/03-cli.md#install

**Comment by raamdev** [comment]
Related: https://github.com/websharks/phings/issues/88

**Comment by jaswrks** [comment]
Resolved in the release of v160526.
https://github.com/websharks/phings/releases/tag/160526
