### ISSUE TITLE
Lite generation does not change Plugin Name token

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#95]
Testing Phings v160418 against the dev branch of Comet Cache Pro, I found that running `phing build-all` or `phing full-build-all` does not change the `Plugin Name:` token at the top of the main Lite plugin file:

`.~build/comet-cache/.~build/comet-cache/comet-cache.php`

```
<?php
/*
Version: 160510
Text Domain: comet-cache
Plugin Name: Comet Cache Pro
Network: true

Author: WebSharks, Inc.
Author URI: http://websharks-inc.com/
```

Notice how it still says `Comet Cache Pro`, when it should just say `Comet Cache` (this is the Lite version).

---

This bug is caused by [this line](https://github.com/websharks/phings/blob/160418/src/psr4/setups/patterns/wp-token.xml#L22), which describes only `${project_slug}.php`, when what we also need is `${project_lite_slug}.php`. It doesn't make sense to add the Lite slug to `_wp_token_pattern_set`, since it may not be applicable in every context (and PatternSet does not support If/Then), so I suggest we simply add an include after [this line](https://github.com/websharks/phings/blob/160418/src/psr4/targets/variations/lite/prepare.xml#L88):

```
<include pattern="${project_lite_slug}.php" />
```

I have confirmed the above fixes the problem.

**Comment by jaswrks** [comment]
Next Release Changelog:
- Bug fix in lite patterns. See: https://github.com/websharks/phings/issues/95
